version: '3'
services:
  api-sample-python:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: api-sample-python:${TAG:-latest}
    volumes:
      - ./api:/app/api
    env_file:
      - .env
