version: '3'
services:
  api-sample-nodejs:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: api-sample-nodejs:${TAG:-latest}
    volumes:
      - ./app:/app
    env_file:
      - .env
