version: '3'
services:
  btse-api-nodejs:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: btse-api-nodejs:${TAG:-latest}
    volumes:
      - ./app:/app
    env_file:
      - .env
