.DEFAULT_GOAL:=help
.PHONY: help
help: ## display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\n'$(HELP_DESC)'\n\nUsage: make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*##/ { printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

